include: package:flutter_lints/flutter.yaml

# Additional lints for better code quality
linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
    unused_catch_clause: ignore
